### ISSUE TITLE
Windows RuntimeError: Can't locate conda executable

### ISSUE THREAD

**Issue by deparkes** [tox-dev/tox-conda#30]
Thanks very much for making this plugin!

I'm running Windows with:
tox==3.13.2
git+git@github.com:tox-dev/tox-conda.git@bc9f4a341a8b8d7aeb8cb5f7574a3906ff06fe9d#egg=tox_conda

and I have been trying to run the tests after cloning the repository.

I created a new conda environment 'tox-conda' with

``` 
conda create --name tox-conda python=3.7
```
And ran the tox-conda tests with 
tox -e py37

This resulted in an error:
```
    raise RuntimeError("Can't locate conda executable")
RuntimeError: Can't locate conda executable
```
To make a bit of progress I tried to modify plugin.py so that the _find_conda_ method simply returns 'conda' which is the command I would naively expect to work.
```
def find_conda(action):
    return "conda"
```
which does seem to work ok, at least the tox-conda tests seem to pass (actually I'm having issues with missing pytest-timeout being missing in the test environment, but I can sort that out separately)
Of course I'd like it to work without having to modify plugin.py - I'm not sure if I've got something configured incorrectly, or if there is an issue with how find_conda() works on windows? or something else?

**Comment by joaomcteixeira** [comment]
Hello,
I am running through the same problem when trying to run tox with tox-conda on appveyor
```
raise RuntimeError("Can't locate conda executable")
RuntimeError: Can't locate conda executable
```

**appveyor.yml**
```
# appveyor.yml
---
environment:
  matrix:
  - TOXENV: py35
    PYTHON_HOME: C:\Python35
    PYTHON_VERSION: '3.5'
  - TOXENV: py36
    PYTHON_HOME: C:\Python36
    PYTHON_VERSION: '3.6'
  - TOXENV: py37
    PYTHON_HOME: C:\Python37
    PYTHON_VERSION: '3.7'

build: off

install:
- '%PYTHON_HOME%\python -m pip install --upgrade pip'
- '%PYTHON_HOME%\Scripts\pip install tox'
- '%PYTHON_HOME%\Scripts\pip install git+git://github.com/tox-dev/tox-conda#egg=tox-conda'

test_script:
- '%PYTHON_HOME%\Scripts\tox'
```

full log [here](https://ci.appveyor.com/project/joaomcteixeira/taurenmd/build/job/5xku4vy20mv8wbf0).

Thank you in advance for all the help
